apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: skipper-ingress-redis
    version: v4.0.9
  name: skipper-ingress-redis
  namespace: kube-system
spec:
  replicas: {{if eq .ConfigItems.skipper_clusterratelimit "true"}}2{{else}}0{{end}}
  selector:
    matchLabels:
      application: skipper-ingress-redis
  serviceName: skipper-ingress-redis
  template:
    metadata:
      labels:
        application: skipper-ingress-redis
        version: v4.0.9
    spec:
{{- if eq .Cluster.ConfigItems.system_pods_critical "true" }}
      priorityClassName: system-cluster-critical
{{- end }}
      containers:
      - image: registry.opensource.zalan.do/zmon/redis:4.0.9-master-6
        name: skipper-ingress-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Cluster.ConfigItems.skipper_redis_cpu }}
            memory: {{ .Cluster.ConfigItems.skipper_redis_memory }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
